import { BeginnerStaple } from './foodLogTypes';

export const BEGINNER_STAPLES: BeginnerStaple[] = [
  {
    id: 's1',
    title: 'Grilled Chicken & White Rice',
    subtitle: '150g breast · 1 cup steamed rice · 1/2 cup broccoli',
    calories: 410,
    protein: 42,
    carbs: 45,
    fat: 4,
    recommendedFor: 'MUSCLE_GAIN',
    badge: 'High Protein Staple',
    icon: '🍗',
  },
  {
    id: 's2',
    title: 'Whey Protein Shake & Banana',
    subtitle: '1 scoop whey protein (25g) · 1 medium banana · water',
    calories: 225,
    protein: 26,
    carbs: 28,
    fat: 2,
    recommendedFor: 'BOTH',
    badge: 'Post-Workout Fuel',
    icon: '🥛',
  },
  {
    id: 's3',
    title: 'Boiled Eggs & Whole Wheat Toast',
    subtitle: '2 large whole eggs · 2 slices whole wheat toast',
    calories: 290,
    protein: 18,
    carbs: 24,
    fat: 11,
    recommendedFor: 'BOTH',
    badge: 'Classic Breakfast',
    icon: '🍳',
  },
  {
    id: 's4',
    title: 'Greek Yogurt with Berries & Honey',
    subtitle: '170g non-fat Greek yogurt · 1/2 cup berries · 1 tsp honey',
    calories: 185,
    protein: 19,
    carbs: 23,
    fat: 1,
    recommendedFor: 'WEIGHT_LOSS',
    badge: 'Low Calorie & High Protein',
    icon: '🫐',
  },
  {
    id: 's5',
    title: 'Tuna & Avocado Mixed Salad',
    subtitle: '1 can chunk light tuna · 1/2 avocado · mixed greens & lemon',
    calories: 280,
    protein: 34,
    carbs: 8,
    fat: 13,
    recommendedFor: 'WEIGHT_LOSS',
    badge: 'Lean Fat Loss',
    icon: '🥗',
  },
  {
    id: 's6',
    title: 'Oatmeal with Peanut Butter',
    subtitle: '1 cup cooked oats · 1 tbsp natural peanut butter · cinnamon',
    calories: 330,
    protein: 11,
    carbs: 48,
    fat: 12,
    recommendedFor: 'MUSCLE_GAIN',
    badge: 'Slow-Digesting Energy',
    icon: '🥣',
  },
  {
    id: 's7',
    title: 'Salmon Fillet & Roasted Sweet Potato',
    subtitle: '150g baked salmon · 150g baked sweet potato',
    calories: 420,
    protein: 35,
    carbs: 32,
    fat: 16,
    recommendedFor: 'MUSCLE_GAIN',
    badge: 'Omega-3 Rich Recovery',
    icon: '🐟',
  },
  {
    id: 's8',
    title: 'Cottage Cheese & Apple Slices',
    subtitle: '1 cup low-fat cottage cheese · 1 sliced red apple',
    calories: 220,
    protein: 24,
    carbs: 26,
    fat: 2,
    recommendedFor: 'WEIGHT_LOSS',
    badge: 'Casein Night Snack',
    icon: '🍏',
  },
];
